services:
  db: 
    image: mongo:4.2
    container_name: db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: carrofacildb
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password